### ISSUE TITLE
[Bug] On Install on Synology

### ISSUE THREAD

**Issue by Arthuro87** [wimleers/homebridge-sma-home-manager#24]
Please make it run on a Synology DSM. On Synology you can run the Package Homebridge. 

Running post-install scripts...

> @serialport/bindings@8.0.8 install
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/Node.js_v20/usr/local/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-sma-home-manager/node_modules/@serialport/bindings
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-sma-home-manager/node_modules/@serialport/bindings
npm ERR! command failed
npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

**Comment by SpaceDragon1205** [comment]
Same at me. Using a Synology DS720+ and it's not possible to install this Plugin. Same failure.
